site:
  title: Technium Docs
  start_page: terraform-infra::index.adoc
content:
  sources:
  - url: https://github.com/techniumlabs/terraform-infra.git
    branches: [antora-doc]
    start_path: docs
  - url: https://github.com/techniumlabs/kustomize-base.git
    branches: [antora]
    start_path: docs
  - url: https://github.com/techniumlabs/containers.git
    branches: [antora]
    start_path: docs
  - url: https://github.com/techniumlabs/docs.git
    branches: [antora]
ui:
  bundle:
    url: ./antora-ui-default-master/build/ui-bundle.zip
    snapshot: true
